### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS#15]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by Pamela-rugel** [comment]
Dear Customer. We have received your new additions to the business rule, we will start working on them.

**Comment by Pamela-rugel** [comment]
The issue has been categorized.

**Comment by Pamela-rugel** [comment]
The issue has been categorized.

**Comment by Pamela-rugel** [comment]
We will proceed to process the request, @DennisseAguirre will be the assigned analyst, @alejandraquimi will develop the solution, and @Pamela-rugel will perform the tests

**Comment by DennisseAguirre** [comment]
[Impact_Analysis_issues_15.docx](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/files/10442156/Impact_Analysis_issues_15.docx)
Good evening, customer. Here is the impact analysis. @pmaldonado-espol

**Comment by alejandraquimi** [comment]
@Pamela-rugel , @DennisseAguirre The first implementation with the changes of the new rules on commit [34348e9](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/commit/34348e964ac846c1533f7f9c8b96ddeb1d6f26a4)
Please check out and test them.
https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/blob/34348e964ac846c1533f7f9c8b96ddeb1d6f26a4/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L51-L56

**Comment by pmaldonado-espol** [comment]
> [Impact_Analysis_issues_15.docx](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/files/10442156/Impact_Analysis_issues_15.docx)
> Good evening, customer. Here is the impact analysis. @pmaldonado-espol

It’s Okay.

**Comment by Pamela-rugel** [comment]
@alejandraquimi  The code has passed all the tests.
[Testing_Plan_Pamela.pdf](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/files/10458316/Testing_Plan_Pamela.pdf)

**Comment by Pamela-rugel** [comment]
Dear customer @pmaldonado-espol , I have attached the acceptance test plan for the new features and also the instructions to run the program. Let me know if more requirements are needed or if there were any problems.
[Acceptance_Testing.pdf](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/files/10458339/Acceptance_Testing.pdf)

**Comment by pmaldonado-espol** [comment]
> Dear customer @pmaldonado-espol , I have attached the acceptance test plan for the new features and also the instructions to run the program. Let me know if more requirements are needed or if there were any problems.
> [Acceptance_Testing.pdf](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/files/10458339/Acceptance_Testing.pdf)

The implementation is according with the requested changes, thank you.

**Comment by Pamela-rugel** [comment]
Thank you @pmaldonado-espol . All the steps have been verified and the solution is complete. @alejandraquimi will release the new version of the software for you with proper instructions for its use.

**Comment by alejandraquimi** [comment]
Hello! @pmaldonado-espol we have made all the changes requested, we've created a compiled executable. In order to download it you have to go to release page [v1.0](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/releases/tag/v1.0) , In there is described the requirements and the steps to follow and run the program.

If you have doubts, you can write to me.

**Comment by pmaldonado-espol** [comment]
> Hello! @pmaldonado-espol we have made all the changes requested, we've created a compiled executable. In order to download it you have to go to release page [v1.0](https://github.com/Pamela-rugel/ISII-WORKSHOPS-INVENTARIO_FACTURACION_VENTAS/releases/tag/v1.0) , In there is described the requirements and the steps to follow and run the program.
> 
> If you have doubts, you can write to me.

No more changes are needed. Thank you.
